name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-treinamento-01
  LOCATION: eastus
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: c6e92b95-0d02-42a1-b8f5-e07881d3a548
  WEBAPP_NAME: eshoponweb-webapp-yago

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload artifact for deployment job (app)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload artifact for deployment job (bicep)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download artifact from build job (.NET App)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download artifact from build job (Bicep)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: List files for debugging
        run: ls -R

      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure with Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: >
            webAppName=${{ env.WEBAPP_NAME }}
            location=${{ env.LOCATION }}
          failOnStdErr: false

      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
