name: eShopOnWeb Build and Deploy

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-treinamento-01
  LOCATION: eastus
  TEMPLATE_FILE: infra/webapp.bicep
  PARAMETERS_FILE: infra/parameters.json
  SUBSCRIPTION_ID: c6e92b95-0d02-42a1-b8f5-e07881d3a548
  WEBAPP_NAME: eshoponweb-webapp-myeggs

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build project
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test project
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: Publish app
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ./publish
          cd ./publish
          zip -r ../app.zip .

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: app.zip

      - name: Upload Bicep template
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: |
            ${{ env.TEMPLATE_FILE }}
            ${{ env.PARAMETERS_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: dotnet-app

      - name: Download Bicep template
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable CLI debug
        run: az config set core.only_show_errors=false

      - name: Validate Bicep template
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group validate \
              --subscription ${{ env.SUBSCRIPTION_ID }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --template-file bicep-template/webapp.bicep \
              --parameters bicep-template/parameters.json

      - name: Deploy with Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: bicep-template/parameters.json
          failOnStdErr: false

      - name: Deploy app via CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path dotnet-app/app.zip \
              --type zip
